name: docker-images

on:
  push:
    branches: 
    - master
    - docker-test
  pull_request:
    branches: 
    - master
    - docker-test

jobs:
  multi:
            
    runs-on: ubuntu-latest
    steps:
      - 
        name: Determin docker tag
        env:
          TAG_NAME: ${{ github.ref }}
        run: |
          if [ "${TAG_NAME##*/}" = "master" ]; then
            tag=latest
          else
            tag=build-test
          fi
          echo "docker_tag=${tag}" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Prevent from loading rubygems from TUNA
        run: |
          sed -i "/^source/c source 'https://rubygems.org'" Gemfile
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        if: github.event_name == 'push'
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-mirrorweb-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-mirrorweb-
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        if: github.event_name == 'pull_request'
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-pr-${{ github.event.pull_request.head.user.login }}-buildx-mirrorweb-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-pr-${{ github.event.pull_request.head.user.login }}-buildx-mirrorweb-
            ${{ runner.os }}-buildx-mirrorweb-
      -
        name: Cache Docker layers
        if: github.event_name != 'push' && github.event_name != 'pull_request'
        run: |
          echo "I do not know how to setup cache"
          exit -1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        if: github.event_name == 'push'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.build
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          tags: tunathu/mirror-web:${{ env.docker_tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
